// frontend/src/views/auth/Login.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import type { LoginRequest } from '@/types'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

const form = reactive<LoginRequest>({
  email: '',
  password: ''
})

const formRef = ref()
const loading = ref(false)
const showPassword = ref(false)

const formRules = {
  email: [
    { required: true, message: '请输入邮箱' },
    { email: true, message: '请输入正确的邮箱格式' }
  ],
  password: [
    { required: true, message: '请输入密码' },
    { min: 6, message: '密码至少6个字符', type: 'warning' }
  ]
}

const handleSubmit = async () => {
  const valid = await formRef.value.validate()
  if (valid !== true) return

  loading.value = true
  const success = await authStore.login(form)
  loading.value = false

  if (success) {
    const redirect = route.query.redirect as string || '/tasks'
    router.push(redirect)
  }
}

const goToRegister = () => {
  router.push('/register')
}
</script>

<template>
  <div class="login-container">
    <div class="login-box">
      <h1 class="title">TASK</h1>
      <p class="subtitle">登录您的账户</p>

      <t-form
        ref="formRef"
        :data="form"
        :rules="formRules"
        label-width="0"
        @submit="handleSubmit"
      >
        <t-form-item name="email">
          <t-input
            v-model="form.email"
            placeholder="请输入邮箱"
            type="email"
            clearable
            size="large"
          >
            <template #prefix-icon>
              <t-icon name="mail" />
            </template>
          </t-input>
        </t-form-item>

        <t-form-item name="password">
          <t-input
            v-model="form.password"
            placeholder="请输入密码"
            :type="showPassword ? 'text' : 'password'"
            clearable
            size="large"
          >
            <template #prefix-icon>
              <t-icon name="lock-on" />
            </template>
            <template #suffix-icon>
              <t-icon
                :name="showPassword ? 'view' : 'view-off'"
                style="cursor: pointer"
                @click="showPassword = !showPassword"
              />
            </template>
          </t-input>
        </t-form-item>

        <t-form-item>
          <t-button
            theme="primary"
            type="submit"
            size="large"
            :loading="loading"
            block
          >
            登录
          </t-button>
        </t-form-item>

        <div class="footer-links">
          <span>还没有账户？</span>
          <t-link theme="primary" @click="goToRegister">立即注册</t-link>
        </div>
      </t-form>
    </div>
  </div>
</template>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #fff 60%, var(--td-brand-color-1) 100%);
}

.login-box {
  width: 400px;
  padding: 40px;
  background: white;
  border-radius: var(--td-radius-default);
  border: 1px solid var(--td-gray-color-4);
}

.title {
  font-size: 28px;
  font-weight: 600;
  text-align: center;
  margin-bottom: 8px;
  color: #333;
}

.subtitle {
  font-size: 14px;
  color: #666;
  text-align: center;
  margin-bottom: 32px;
}

.footer-links {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 8px;
  margin-top: 16px;
  font-size: 14px;
  color: #666;
}

.footer-links a {
  cursor: pointer;
}
</style>

// frontend/src/views/auth/Login.tsx
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router'
import { Button, Form, Typography } from '@douyinfe/semi-ui-19'
import { IconLock, IconMail } from '@douyinfe/semi-icons'
import { useAuthStore } from '@/stores/auth'
import type { LoginRequest } from '@/types'
import styles from './auth.module.css'

export default function Login() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [loading, setLoading] = useState(false)

  // Semi Form 校验通过后才会触发 onSubmit
  const handleSubmit = async (values: Record<string, unknown>) => {
    setLoading(true)
    const success = await useAuthStore.getState().login(values as unknown as LoginRequest)
    setLoading(false)

    if (success) {
      const redirect = searchParams.get('redirect') || '/tasks'
      navigate(redirect)
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.box}>
        <h1 className={styles.title}>TASK</h1>
        <p className={styles.subtitle}>登录您的账户</p>

        <Form onSubmit={handleSubmit} disabled={loading}>
          <Form.Input
            field="email"
            noLabel
            size="large"
            placeholder="请输入邮箱"
            showClear
            prefix={<IconMail />}
            rules={[
              { required: true, message: '请输入邮箱' },
              { type: 'email', message: '请输入正确的邮箱格式' }
            ]}
          />
          <Form.Input
            field="password"
            noLabel
            size="large"
            placeholder="请输入密码"
            mode="password"
            prefix={<IconLock />}
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少6个字符' }
            ]}
          />
          <div className={styles.submitRow}>
            <Button htmlType="submit" theme="solid" type="primary" size="large" loading={loading} block>
              登录
            </Button>
          </div>

          <div className={styles.footerLinks}>
            <span>还没有账户？</span>
            <Typography.Text link={{ onClick: () => navigate('/register') }}>立即注册</Typography.Text>
          </div>
        </Form>
      </div>
    </div>
  )
}
