// frontend/src/views/task-list/TaskListManage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useTaskListStore } from '@/stores/taskList'
import type { TaskList } from '@/types'
import { DialogPlugin } from 'tdesign-vue-next'
import type { PrimaryTableCol } from 'tdesign-vue-next'
import TaskListForm from '@/components/task-list/TaskListForm.vue'

const taskListStore = useTaskListStore()

const lists = computed(() => taskListStore.lists)
const loading = computed(() => taskListStore.loading)
const total = computed(() => taskListStore.total)

// Pagination
const pagination = ref({
  current: 1,
  pageSize: 20
})

// Table columns
const columns: PrimaryTableCol[] = [
  { colKey: 'sort_order', title: '序号', width: 80 },
  { colKey: 'id', title: 'ID', width: 240 },
  { colKey: 'title', title: '标题', width: 220 },
  { colKey: 'description', title: '描述', width: 300 },
  { colKey: 'creator', title: '创建者', width: 120 },
  { colKey: 'created_at', title: '创建时间', width: 180 },
  { colKey: 'updated_at', title: '更新时间', width: 180 },
  { colKey: 'action', title: '操作', width: 120, fixed: 'right' }
]

// Fetch task lists
const fetchLists = async () => {
  await taskListStore.fetchLists({
    page: pagination.value.current,
    page_size: pagination.value.pageSize
  })
}

// Open create dialog
const createFormRef = ref<InstanceType<typeof TaskListForm>>()
const showCreateDialog = ref(false)
const openCreateDialog = () => {
  showCreateDialog.value = true
}

// Handle create task list
const handleCreateList = async (data: any) => {
  await taskListStore.createList(data)
  showCreateDialog.value = false
  fetchLists()
}

// Open edit dialog
const editFormRef = ref<InstanceType<typeof TaskListForm>>()
const editingList = ref<TaskList | null>(null)
const showEditDialog = ref(false)
const openEditDialog = (list: TaskList) => {
  editingList.value = list
  showEditDialog.value = true
}

// Handle update task list
const handleUpdateList = async (data: any) => {
  if (editingList.value) {
    await taskListStore.updateList(editingList.value.id, data)
    showEditDialog.value = false
    editingList.value = null
    fetchLists()
  }
}

// Handle delete task list
const handleDeleteList = (list: TaskList) => {
  const dialog = DialogPlugin.confirm({
    header: '确认删除',
    body: `确定要删除任务清单 "${list.title}" 吗？该清单下的任务将移动到默认清单。`,
    confirmBtn: '确定',
    cancelBtn: '取消',
    onConfirm: async () => {
      const success = await taskListStore.deleteList(list.id)
      dialog.hide()
      if (success) {
        fetchLists()
      }
    },
  })
}

// Format date
const formatDate = (dateStr: string) => {
  const date = new Date(dateStr)
  return date.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

// Pagination change
const onPageChange = (pageInfo: any) => {
  pagination.value.current = pageInfo.current
  fetchLists()
}

// On mounted
onMounted(() => {
  fetchLists()
})
</script>

<template>
  <div class="task-list-manage-container">
    <!-- Header -->
    <div class="page-header">
      <div class="title">任务清单</div>
      <t-button theme="primary" @click="openCreateDialog">
        <template #icon><t-icon name="add" /></template>
        新建清单
      </t-button>
    </div>

    <!-- Task List Table -->
    <div class="table-container">
      <t-table
        :data="lists"
        :columns="columns"
        :loading="loading"
        :header-affixed-top="{ container: '.table-container' }"
        :pagination="{
          current: pagination.current,
          pageSize: pagination.pageSize,
          total: total,
          showPageSize: false
        }"
        row-key="id"
        hover
        @page-change="onPageChange"
      >
        <template #id="{ row }">
          <span class="list-id">{{ row.id }}</span>
        </template>

        <template #title="{ row }">
          <div class="list-title">
            <span>{{ row.title }}</span>
            <t-tag v-if="row.is_default" theme="primary" variant="light" size="small">默认</t-tag>
          </div>
        </template>

        <template #description="{ row }">
          <span class="list-desc">{{ row.description || '-' }}</span>
        </template>

        <template #creator="{ row }">
          <div class="creator-info">
            <t-avatar :image="row.creator?.avatar || ''" size="24">
              {{ row.creator?.username?.charAt(0) || 'U' }}
            </t-avatar>
            <span>{{ row.creator?.username || '-' }}</span>
          </div>
        </template>

        <template #created_at="{ row }">
          {{ formatDate(row.created_at) }}
        </template>

        <template #updated_at="{ row }">
          {{ formatDate(row.updated_at) }}
        </template>

        <template #action="{ row }">
          <t-space size="medium">
            <t-link theme="primary" hover="color" @click="openEditDialog(row)">
              编辑
            </t-link>
            <t-link
              v-if="!row.is_default"
              theme="danger"
              hover="color"
              @click="handleDeleteList(row)"
            >
              删除
            </t-link>
          </t-space>
        </template>
      </t-table>

      <!-- Empty State -->
      <div v-if="!loading && lists.length === 0" class="empty-state">
        <t-icon name="info-circle" size="48px" />
        <p>暂无任务清单</p>
        <t-button theme="primary" variant="outline" @click="openCreateDialog">
          创建第一个清单
        </t-button>
      </div>
    </div>

    <!-- Create Dialog -->
    <t-dialog
      v-model:visible="showCreateDialog"
      header="新建清单"
      width="min(92vw, 640px)"
      cancel-btn="取消"
      confirm-btn="确定"
      @confirm="createFormRef?.submit()"
      @cancel="showCreateDialog = false"
    >
      <TaskListForm ref="createFormRef" @submit="handleCreateList" />
    </t-dialog>

    <!-- Edit Dialog -->
    <t-dialog
      v-model:visible="showEditDialog"
      header="编辑清单"
      width="min(92vw, 640px)"
      cancel-btn="取消"
      confirm-btn="确定"
      @confirm="editFormRef?.submit()"
      @cancel="showEditDialog = false; editingList = null"
    >
      <TaskListForm
        ref="editFormRef"
        :list="editingList"
        @submit="handleUpdateList"
      />
    </t-dialog>
  </div>
</template>

<style scoped>
.task-list-manage-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: 24px;
  box-sizing: border-box;
  background: var(--td-bg-color-page);
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  flex-shrink: 0;
}

.title {
  font-size: 24px;
  font-weight: 600;
  color: var(--td-text-color-primary);
}

.table-container {
  flex: 1;
  min-height: 0;
  overflow: auto;
  position: relative;
  background: var(--td-bg-color-container);
  border: 0;
  border-radius: var(--td-radius-default);
  padding: 0;
}

.list-id {
  font-family: monospace;
  font-size: 12px;
  color: var(--td-text-color-secondary);
}

.list-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 500;
  color: var(--td-text-color-primary);
}

.list-desc {
  font-size: 13px;
  color: var(--td-text-color-secondary);
  white-space: normal;
  word-break: break-word;
}

.creator-info {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--td-text-color-primary);
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 24px;
  color: var(--td-text-color-secondary);
}

.empty-state p {
  margin: 16px 0;
  font-size: 14px;
}
</style>

// frontend/src/views/task-list/TaskListManage.tsx
import { useEffect, useRef, useState } from 'react'
import { Button, Modal, Space, Table, Tag, Typography } from '@douyinfe/semi-ui-19'
import type { ColumnProps } from '@douyinfe/semi-ui-19/lib/es/table'
import { IconInfoCircle, IconPlus } from '@douyinfe/semi-icons'
import { useTaskListStore } from '@/stores/taskList'
import type { CreateTaskListRequest, TaskList, UpdateTaskListRequest } from '@/types'
import TaskListForm, { type TaskListFormHandle } from '@/components/task-list/TaskListForm'
import styles from './TaskListManage.module.css'

const formatDate = (dateStr: string) => {
  return new Date(dateStr).toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const PAGE_SIZE = 20

export default function TaskListManage() {
  // useModal 渲染在组件树内,避免静态 Modal.confirm 在 React 19 下同步卸载 root 的告警
  const [modal, modalContextHolder] = Modal.useModal()
  const lists = useTaskListStore((s) => s.lists)
  const loading = useTaskListStore((s) => s.loading)
  const total = useTaskListStore((s) => s.total)

  const [page, setPage] = useState(1)

  const fetchLists = (p?: number) => {
    return useTaskListStore.getState().fetchLists({ page: p ?? page, page_size: PAGE_SIZE })
  }

  useEffect(() => {
    fetchLists(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Create dialog
  const createFormRef = useRef<TaskListFormHandle>(null)
  const [showCreateDialog, setShowCreateDialog] = useState(false)

  const handleCreateList = async (data: CreateTaskListRequest | UpdateTaskListRequest) => {
    await useTaskListStore.getState().createList(data as CreateTaskListRequest)
    setShowCreateDialog(false)
    fetchLists()
  }

  // Edit dialog
  const editFormRef = useRef<TaskListFormHandle>(null)
  const [editingList, setEditingList] = useState<TaskList | null>(null)
  const [showEditDialog, setShowEditDialog] = useState(false)
  const openEditDialog = (list: TaskList) => {
    setEditingList(list)
    setShowEditDialog(true)
  }
  const closeEditDialog = () => {
    setShowEditDialog(false)
    setEditingList(null)
  }

  const handleUpdateList = async (data: CreateTaskListRequest | UpdateTaskListRequest) => {
    if (!editingList) return
    await useTaskListStore.getState().updateList(editingList.id, data)
    closeEditDialog()
    fetchLists()
  }

  // Handle delete task list
  const handleDeleteList = (list: TaskList) => {
    modal.confirm({
      title: '确认删除',
      content: `确定要删除任务清单 "${list.title}" 吗？该清单下的任务将移动到默认清单。`,
      okText: '确定',
      cancelText: '取消',
      onOk: async () => {
        const success = await useTaskListStore.getState().deleteList(list.id)
        if (success) {
          fetchLists()
        }
      }
    })
  }

  const columns: ColumnProps<TaskList>[] = [
    { title: '序号', dataIndex: 'sort_order', width: 80 },
    {
      title: 'ID',
      dataIndex: 'id',
      width: 240,
      render: (v: string) => <span className={styles.listId}>{v}</span>
    },
    {
      title: '标题',
      dataIndex: 'title',
      width: 220,
      render: (_: unknown, row: TaskList) => (
        <div className={styles.listTitle}>
          <span>{row.title}</span>
          {row.is_default && (
            <Tag color="blue" size="small">
              默认
            </Tag>
          )}
        </div>
      )
    },
    {
      title: '描述',
      dataIndex: 'description',
      width: 300,
      render: (v: string) => <span className={styles.listDesc}>{v || '-'}</span>
    },
    {
      title: '创建者',
      dataIndex: 'creator',
      width: 120,
      render: (_: unknown, row: TaskList) => <span className={styles.creatorInfo}>{row.creator?.username || '-'}</span>
    },
    { title: '创建时间', dataIndex: 'created_at', width: 180, render: (v: string) => formatDate(v) },
    { title: '更新时间', dataIndex: 'updated_at', width: 180, render: (v: string) => formatDate(v) },
    {
      title: '操作',
      dataIndex: 'action',
      width: 120,
      className: styles.actionCell,
      render: (_: unknown, row: TaskList) => (
        <Space spacing={12}>
          <Typography.Text link={{ onClick: () => openEditDialog(row) }}>编辑</Typography.Text>
          {!row.is_default && (
            <Typography.Text link={{ onClick: () => handleDeleteList(row) }} type="danger">
              删除
            </Typography.Text>
          )}
        </Space>
      )
    }
  ]

  return (
    <div className={styles.container}>
      {modalContextHolder}
      {/* Header */}
      <div className={styles.pageHeader}>
        <div className={styles.title}>任务清单</div>
        <Button theme="solid" type="primary" icon={<IconPlus />} onClick={() => setShowCreateDialog(true)}>
          新建清单
        </Button>
      </div>

      {/* Task List Table */}
      <div className={styles.tableContainer}>
        <Table
          dataSource={lists}
          columns={columns}
          loading={loading}
          rowKey="id"
          pagination={{
            currentPage: page,
            pageSize: PAGE_SIZE,
            total,
            onPageChange: (p: number) => {
              setPage(p)
              fetchLists(p)
            }
          }}
        />

        {/* Empty State */}
        {!loading && lists.length === 0 && (
          <div className={styles.emptyState}>
            <IconInfoCircle style={{ fontSize: 48 }} />
            <p>暂无任务清单</p>
            <Button type="primary" onClick={() => setShowCreateDialog(true)}>
              创建第一个清单
            </Button>
          </div>
        )}
      </div>

      {/* Create Dialog */}
      <Modal
        visible={showCreateDialog}
        title="新建清单"
        centered
        width="min(92vw, 640px)"
        okText="确定"
        cancelText="取消"
        onOk={() => createFormRef.current?.submit()}
        onCancel={() => setShowCreateDialog(false)}
      >
        <TaskListForm ref={createFormRef} onSubmit={handleCreateList} />
      </Modal>

      {/* Edit Dialog */}
      <Modal
        visible={showEditDialog}
        title="编辑清单"
        centered
        width="min(92vw, 640px)"
        okText="确定"
        cancelText="取消"
        onOk={() => editFormRef.current?.submit()}
        onCancel={closeEditDialog}
      >
        <TaskListForm key={editingList?.id || 'edit'} ref={editFormRef} list={editingList} onSubmit={handleUpdateList} />
      </Modal>
    </div>
  )
}
