// frontend/src/components/task-list/TaskListForm.tsx
import { useImperativeHandle, useRef, type Ref } from 'react'
import { Form } from '@douyinfe/semi-ui-19'
import type { FormApi } from '@douyinfe/semi-ui-19/lib/es/form'
import type { TaskList, CreateTaskListRequest, UpdateTaskListRequest } from '@/types'

export interface TaskListFormHandle {
  submit: () => void
}

interface Props {
  list?: TaskList | null
  onSubmit: (data: CreateTaskListRequest | UpdateTaskListRequest) => void
  // 父级弹窗底部按钮经此句柄触发校验+提交；编辑/新建切换时父级用 key 重挂载本组件
  ref?: Ref<TaskListFormHandle>
}

export default function TaskListForm({ list, onSubmit, ref }: Props) {
  const formApiRef = useRef<FormApi | null>(null)

  const initValues = {
    title: list?.title ?? '',
    description: list?.description ?? '',
    sort_order: list?.sort_order ?? undefined
  }

  const handleSubmit = async () => {
    const api = formApiRef.current
    if (!api) return
    try {
      await api.validate()
    } catch {
      return
    }
    const values = api.getValues()
    onSubmit({
      title: values.title,
      description: values.description || undefined,
      sort_order: values.sort_order ?? undefined
    })
  }

  useImperativeHandle(ref, () => ({ submit: handleSubmit }))

  return (
    <Form
      getFormApi={(api) => (formApiRef.current = api)}
      initValues={initValues}
      labelPosition="left"
      labelWidth={80}
      onSubmit={handleSubmit}
    >
      <Form.Input
        field="title"
        label="标题"
        placeholder="请输入清单标题"
        maxLength={255}
        rules={[
          { required: true, message: '请输入清单标题' },
          { min: 1, max: 255, message: '标题长度应为1-255个字符' }
        ]}
      />

      <Form.InputNumber
        field="sort_order"
        label="序号"
        min={1}
        max={10000000}
        placeholder="留空自动排在最后"
        style={{ width: '100%' }}
        rules={[
          {
            validator: (_rule: unknown, val: unknown) =>
              val === undefined || val === null || val === '' ||
              (Number.isInteger(val) && (val as number) >= 1 && (val as number) <= 10000000),
            message: '序号应为1-10000000的整数'
          }
        ]}
      />

      <Form.TextArea
        field="description"
        label="描述"
        placeholder="请输入清单描述"
        maxCount={5000}
        autosize={{ minRows: 4, maxRows: 14 }}
        rules={[{ max: 5000, message: '描述最多5000个字符' }]}
      />
    </Form>
  )
}

// frontend/src/components/task-list/TaskListForm.vue
<script setup lang="ts">
import { ref, reactive, watch } from 'vue'
import type { TaskList, CreateTaskListRequest, UpdateTaskListRequest } from '@/types'
import type { FormRules } from 'tdesign-vue-next'

interface Props {
  list?: TaskList | null
}

interface Emits {
  (e: 'submit', data: CreateTaskListRequest | UpdateTaskListRequest): void
  (e: 'cancel'): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const formRef = ref()

const form = reactive({
  title: '',
  description: '',
  sort_order: undefined as number | undefined
})

const formRules: FormRules = {
  title: [
    { required: true, message: '请输入清单标题' },
    { min: 1, max: 255, message: '标题长度应为1-255个字符', type: 'warning' }
  ],
  description: [
    { max: 5000, message: '描述最多5000个字符', type: 'warning' }
  ],
  sort_order: [
    {
      validator: (val: unknown) =>
        val === undefined || val === null ||
        (Number.isInteger(val) && (val as number) >= 1 && (val as number) <= 1000),
      message: '序号应为1-1000的整数'
    }
  ]
}

// Populate in edit mode, reset in create mode
watch(() => props.list, (list) => {
  if (list) {
    form.title = list.title
    form.description = list.description || ''
    form.sort_order = list.sort_order
  } else {
    form.title = ''
    form.description = ''
    form.sort_order = undefined
  }
  formRef.value?.reset()
}, { immediate: true })

const handleSubmit = async () => {
  const valid = await formRef.value?.validate()
  if (valid !== true) return

  emit('submit', {
    title: form.title,
    description: form.description || undefined,
    sort_order: form.sort_order ?? undefined
  })
}

// Expose submit so the dialog footer can trigger validation + submit
defineExpose({ submit: handleSubmit })
</script>

<template>
  <t-form
    ref="formRef"
    :data="form"
    :rules="formRules"
    label-width="80px"
    @submit="handleSubmit"
  >
    <t-form-item label="标题" name="title">
      <t-input
        v-model="form.title"
        placeholder="请输入清单标题"
        :maxlength="255"
        show-limit-number
      />
    </t-form-item>

    <t-form-item label="序号" name="sort_order">
      <t-input-number
        v-model="form.sort_order"
        theme="normal"
        :min="1"
        :max="1000"
        :allow-input-over-limit="false"
        placeholder="留空自动排在最后"
        style="width: 100%"
      />
    </t-form-item>

    <t-form-item label="描述" name="description">
      <t-textarea
        v-model="form.description"
        placeholder="请输入清单描述"
        :maxlength="5000"
        :autosize="{ minRows: 4, maxRows: 14 }"
        show-limit-number
      />
    </t-form-item>
  </t-form>
</template>

<style scoped>
.t-form-item {
  margin-bottom: 24px;
}
</style>
