// frontend/src/components/task/ExecutionStatusBadge.tsx
import { Tag } from '@douyinfe/semi-ui-19'
import type { TagColor } from '@douyinfe/semi-ui-19/lib/es/tag'
import type { TaskExecutionStatus } from '@/types'

const statusConfig: Record<TaskExecutionStatus, { label: string; color: TagColor }> = {
  unplanned: { label: '未计划', color: 'grey' },
  planning: { label: '计划中', color: 'orange' },
  planned: { label: '已计划', color: 'blue' },
  working: { label: '工作中', color: 'blue' },
  completed: { label: '已完成', color: 'green' }
}

export default function ExecutionStatusBadge({ status }: { status: TaskExecutionStatus }) {
  const config = statusConfig[status] ?? { label: status, color: 'grey' as TagColor }
  return <Tag color={config.color}>{config.label}</Tag>
}

// frontend/src/components/task/ExecutionStatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { TaskExecutionStatus } from '@/types'

interface Props {
  status: TaskExecutionStatus
}

const props = defineProps<Props>()

const statusConfig: Record<TaskExecutionStatus, { label: string; theme: 'default' | 'primary' | 'warning' | 'success' | 'danger' }> = {
  unplanned: { label: '未计划', theme: 'default' },
  planning: { label: '计划中', theme: 'warning' },
  planned: { label: '已计划', theme: 'primary' },
  working: { label: '工作中', theme: 'primary' },
  completed: { label: '已完成', theme: 'success' }
}

const config = computed(() => statusConfig[props.status] ?? { label: props.status, theme: 'default' as const })
</script>

<template>
  <t-tag :theme="config.theme" variant="light">{{ config.label }}</t-tag>
</template>
