// frontend/src/components/task/PriorityBadge.tsx
import { Tag } from '@douyinfe/semi-ui-19'
import type { TagColor } from '@douyinfe/semi-ui-19/lib/es/tag'
import type { TaskPriority } from '@/types'

const priorityConfig: Record<TaskPriority, { label: string; color: TagColor }> = {
  high: { label: '高', color: 'red' },
  medium: { label: '中', color: 'orange' },
  low: { label: '低', color: 'green' }
}

export default function PriorityBadge({ priority }: { priority: TaskPriority }) {
  const config = priorityConfig[priority] ?? { label: priority, color: 'grey' as TagColor }
  return <Tag color={config.color}>{config.label}</Tag>
}

// frontend/src/components/task/PriorityBadge.vue
<script setup lang="ts">
import type { TaskPriority } from '@/types'

interface Props {
  priority: TaskPriority
}

const props = defineProps<Props>()

const priorityConfig: Record<TaskPriority, { label: string; theme: 'default' | 'primary' | 'warning' | 'success' | 'error' }> = {
  high: { label: '高', theme: 'error' },
  medium: { label: '中', theme: 'warning' },
  low: { label: '低', theme: 'success' }
}

const config = priorityConfig[props.priority]
</script>

<template>
  <t-tag :theme="config.theme" variant="light">{{ config.label }}</t-tag>
</template>
