// frontend/src/components/task/StatusActions.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { Task, TaskStatus } from '@/types'

interface Props {
  task: Task
}

interface Emits {
  (e: 'status-change', status: TaskStatus): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

// Define available status transitions based on current status
const statusActions: Record<TaskStatus, { label: string; value: TaskStatus }[]> = {
  draft: [
    { label: '确认', value: 'pending' },
    { label: '执行', value: 'running' }
  ],
  pending: [
    { label: '执行', value: 'running' },
    { label: '完成', value: 'completed' }
  ],
  running: [
    { label: '暂停', value: 'pending' },
    { label: '完成', value: 'completed' }
  ],
  completed: []
}

const availableActions = computed(() => statusActions[props.task.status] || [])

const handleStatusChange = (status: TaskStatus) => {
  emit('status-change', status)
}
</script>

<template>
  <t-space size="small">
    <t-button
      v-for="action in availableActions"
      :key="action.value"
      size="medium"
      theme="default"
      variant="outline"
      @click="handleStatusChange(action.value)"
    >
      {{ action.label }}
    </t-button>
  </t-space>
</template>

// frontend/src/components/task/StatusActions.tsx
import { Button, Space } from '@douyinfe/semi-ui-19'
import type { Task, TaskStatus } from '@/types'

// Define available status transitions based on current status
const statusActions: Record<TaskStatus, { label: string; value: TaskStatus }[]> = {
  draft: [
    { label: '确认', value: 'pending' },
    { label: '执行', value: 'executing' }
  ],
  pending: [
    { label: '执行', value: 'executing' },
    { label: '完成', value: 'completed' }
  ],
  executing: [
    { label: '完成', value: 'completed' },
    { label: '暂停', value: 'pending' }
  ],
  completed: []
}

// 无操作的状态需在父级跳过渲染，避免空容器产生多余间距
export function hasStatusActions(status: TaskStatus): boolean {
  return (statusActions[status] || []).length > 0
}

interface Props {
  task: Task
  onStatusChange: (status: TaskStatus) => void
}

export default function StatusActions({ task, onStatusChange }: Props) {
  const availableActions = statusActions[task.status] || []
  if (!availableActions.length) return null

  return (
    <Space spacing={8}>
      {availableActions.map((action) => (
        <Button key={action.value} size="small" onClick={() => onStatusChange(action.value)}>
          {action.label}
        </Button>
      ))}
    </Space>
  )
}
