// frontend/src/components/task/StatusBadge.tsx
import { Tag } from '@douyinfe/semi-ui-19'
import type { TagColor } from '@douyinfe/semi-ui-19/lib/es/tag'
import type { TaskStatus } from '@/types'

const statusConfig: Record<TaskStatus, { label: string; color: TagColor }> = {
  draft: { label: '草稿', color: 'grey' },
  pending: { label: '待执行', color: 'orange' },
  executing: { label: '执行中', color: 'blue' },
  completed: { label: '已完成', color: 'green' }
}

export default function StatusBadge({ status }: { status: TaskStatus }) {
  const config = statusConfig[status] ?? { label: status, color: 'grey' as TagColor }
  return <Tag color={config.color}>{config.label}</Tag>
}

// frontend/src/components/task/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { TaskStatus } from '@/types'

interface Props {
  status: TaskStatus
}

const props = defineProps<Props>()

const statusConfig: Record<TaskStatus, { label: string; theme: 'default' | 'primary' | 'warning' | 'success' | 'error' }> = {
  draft: { label: '草稿', theme: 'default' },
  pending: { label: '待执行', theme: 'warning' },
  running: { label: '执行中', theme: 'primary' },
  completed: { label: '已完成', theme: 'success' }
}

const config = computed(() => statusConfig[props.status] ?? { label: props.status, theme: 'default' as const })
</script>

<template>
  <t-tag :theme="config.theme" variant="light">{{ config.label }}</t-tag>
</template>
